version: 0.2
phases:
  pre_build:
    commands:
      - terraform init
      - terraform validate
  
  build:
    commands:
      - terraform apply --auto-approve  | tee /dev/tty | ( ! grep "Error applying plan" )